language: cpp
env:
  global:
    - MINCONDA_VERSION="latest"
    - MINCONDA_LINUX="Linux-x86_64"
    - MINCONDA_OSX="MacOSX-x86_64"
matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
      env: PY=3
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
      env: PY=2
    - os: osx
      osx_image: xcode8
      compiler: clang
      env: PY=3
install:
    # Define the version of miniconda to download
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        MINCONDA_OS=$MINCONDA_LINUX;
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        MINCONDA_OS=$MINCONDA_OSX;
      fi
    - if [[ "$PY" == "3" ]]; then
          wget "http://repo.continuum.io/miniconda/Miniconda3-$MINCONDA_VERSION-$MINCONDA_OS.sh" -O miniconda.sh;
      else
          wget "http://repo.continuum.io/miniconda/Miniconda2-$MINCONDA_VERSION-$MINCONDA_OS.sh" -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Install dependencies
    - conda install cmake xeus=0.18.1 nlohmann_json=3.3.0 cppzmq=4.3.0 xtl=0.5.2 pybind11=2.2.4 jedi=0.13.1 pygments=2.3.1 six=1.12 -c QuantStack -c conda-forge
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
          conda install gcc-7 -c QuantStack -c conda-forge;
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          conda install clangdev -c QuantStack -c conda-forge;
      fi
    # For debugging
    - which python
    - python --version
    # Build and install xeus-python
    - mkdir build
    - cd build
    - cmake -D CMAKE_INSTALL_PREFIX=$HOME/miniconda/ -D DOWNLOAD_GTEST=ON -D PYTHON_EXECUTABLE=`which python` ..
    - make -j2 install
    # Install jupyter_kernel_test and pytest.
    # If Python2, we first create a Python3 environment because jupyter_kernel_test has not Python2 support
    - if [[ "$PY" == "3" ]]; then
          conda install pytest jupyter_kernel_test -c conda-forge;
      else
          conda create --name=tests python=3;
          echo ". $HOME/miniconda/etc/profile.d/conda.sh" >> ~/.bashrc;
          source ~/.bashrc;
          conda activate tests;
          conda install pytest jupyter_kernel_test -c conda-forge;
          jupyter kernelspec install --sys-prefix ../share/jupyter/kernels/xpython;
      fi
script:
    - ./test/test_xeus_python
    - cd ../test && py.test .
