jobs:
  - job: 'Linux'
    strategy:
      matrix:
        py37:
          py_version: 3.7
        py38:
          py_version: 3.8
        py39:
          py_version: 3.9
        static_xeus:
          xpyt_use_shared_xeus: 0
          xpyt_use_shared_xeus_python: 1
        static_xeus_python:
          xpyt_use_shared_xeus: 1
          xpyt_use_shared_xeus_python: 0
        full_static:
          xpyt_use_shared_xeus: 1
          xpyt_use_shared_xeus_python: 1
    pool:
      vmImage: ubuntu-16.04
    timeoutInMinutes: 30
    steps:

      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH

      - template: unix-build.yml
        parameters:
          platform: 'Linux'
